name: Final Project Health Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black autopep8

      - name: Run Flake8 (Lint)
        run: |
          flake8 . || echo "⚠️ Lint warnings detected but not failing build"

      - name: Auto-fix with Black and autopep8
        run: |
          black --line-length 120 .
          autopep8 --in-place --recursive --max-line-length 120 .

      - name: Run final-check.sh
        run: |
          chmod +x final-check.sh
          ./final-check.sh || echo "⚠️ Script completed with warnings"

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-formatting and lint fixes [GitHub Actions]" || echo "No changes to commit"
          git push
