name: Final Project Health Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black autopep8

      - name: Run Flake8 (Lint)
        run: |
          flake8 . || echo "⚠️ Lint warnings detected, continuing..."

      - name: Auto-fix with Black and autopep8
        run: |
          black --line-length 120 .
          autopep8 --in-place --recursive --max-line-length 120 .

      - name: Commit and push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-fix linting issues via GitHub Actions"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "✅ No changes to commit."
          fi
